// ─── BASE DE DATOS TURCAS ────────────────────────────────────────────────
        const baseDeDatosTurcas = [
            // ROMANCE
            { titulo:'Erkenci Kus',          alias:['Pájaro Soñador'],          tmdbQuery:'Erkenci Kus 2018',           nombreKV:'erkenci-kus', genero:'turca-romance', info:'⭐ 8.5 | 🌙 Turca | 📺 51 ep', desc:'Una joven soñadora se enamora de su jefe.' },
            { titulo:'Sen Cal Kapimi',       alias:['Llamas A Mi Puerta'],          tmdbQuery:'Sen Cal Kapimi 2020',        nombreKV:'sen-cal-kapimi', genero:'turca-romance', info:'⭐ 8.6 | 🌙 Turca | 📺 52 ep', desc:'Una estudiante firma un contrato de amor falso con un millonario.' },
            { titulo:'Kiralik Ask',          alias:['Te alquilo mi amor','Amor en alquiler','Kiralik Ask'], tmdbQuery:'Kiralik Ask 2015',           nombreKV:'kiralik-ask', genero:'turca-romance', info:'⭐ 8.2 | 🌙 Turca | 📺 68 ep', desc:'Un millonario contrata a una chica para que finja ser su novia.' },
            { titulo:'Medcezir',                 tmdbQuery:'Medcezir 2013',              nombreKV:'medcezir', genero:'turca-romance', info:'⭐ 8.1 | 🌙 Turca | 📺 72 ep', desc:'Adaptación turca de The OC.' },
            { titulo:'Kara Sevda',               tmdbQuery:'Kara Sevda 2015',            nombreKV:'kara-sevda', genero:'turca-romance', info:'⭐ 8.4 | 🌙 Turca | 📺 74 ep', desc:'Un amor imposible entre dos familias rivales.' },
            { titulo:'Elif',                     tmdbQuery:'Elif 2014',                  nombreKV:'elif', genero:'turca-romance', info:'⭐ 7.8 | 🌙 Turca | 📺 1000+ ep', desc:'Una niña huérfana busca el amor de su familia.' },
            { titulo:'No te enamores',           tmdbQuery:'Una parte de mí 2014',       nombreKV:'no-te-enamores', genero:'turca-romance', info:'⭐ 7.8 | 🌙 Turca | 📺 1000+ ep', desc:'Una familia rica está esperando que su hijo favorito, Kahraman (Özcan Deniz), les de un heredero. Cuando su esposa, Defne (Begüm Kütük Yaşaroğlu), tiene dificultades para concebir, buscan un vientre de alquiler. Elif (Hatice Şendil) está desesperada por conseguir dinero y acepta arrendar su vientre, pero es engañada por la matriarca de la familia Yörükhan. Ella descubre que en realidad es la madre biológica del bebé y emprende una lucha por recuperar a su hijo. Las cosas se complican más por el amor que crece entre Elif y Kahraman, mientras que los Yörükhan se niegan a entregar a su heredero.' },
            { titulo:'contra el Destino',        tmdbQuery:'Kadere Karşı 2022',          nombreKV:'contra-el-destino', genero:'turca-romance', info:'⭐ 7.8 | 🌙 Turca | 📺 1000+ ep', desc:'Una familia .' },
            { titulo:'Mi padre heroe',           tmdbQuery:'Kahraman Babam 2021',        nombreKV:'mi-padre-heroe', genero:'turca-romance', info:'⭐ 5.8 | 🌙 Turca | 📺 + ep', desc:'Vidas peligrosas de los bomberos que se enfrentan a situaciones difíciles.' },
            { titulo:'Doctor Del Pueblo',     tmdbQuery:'Kasaba Doktoru 2022',        nombreKV:'el-doctor-del-pueblo', genero:'turca-romance', info:'⭐ 7.6 | 🌙 Turca | 📺 + ep', desc:'El talentoso y prometedor Ömer, que decidió convertirse en médico tras perder a su padre, y el legendario cirujano Hakan, que se dedica a salvar vidas, se cruzan en un hospital de pueblo alejado de la ciudad.' },
            // DRAMA
            { titulo:'Dirilis Ertugrul',         tmdbQuery:'Dirilis Ertugrul 2014',      nombreKV:'dirilis-ertugrul', genero:'turca-drama', info:'⭐ 8.1 | 🌙 Turca | 📺 150 ep', desc:'Las aventuras del padre del fundador del Imperio Otomano.' },
            { titulo:'Fatih Harbiye',            tmdbQuery:'Fatih Harbiye 2013',         nombreKV:'fatih-harbiye', genero:'turca-drama', info:'⭐ 7.9 | 🌙 Turca | 📺 60 ep', desc:'Una chica entre dos mundos y dos amores.' },
            { titulo:'Cesur ve Guzel',           tmdbQuery:'Cesur ve Guzel 2016',        nombreKV:'cesur-ve-guzel', genero:'turca-drama', info:'⭐ 8.3 | 🌙 Turca | 📺 32 ep', desc:'Un hombre busca vengar la muerte de su padre.' },
            { titulo:'Ezel',                     tmdbQuery:'Ezel 2009',                  nombreKV:'ezel', genero:'turca-drama', info:'⭐ 8.5 | 🌙 Turca | 📺 71 ep', desc:'Un hombre sale de prisión para vengarse de quienes lo traicionaron.' },
            { titulo:'Guzey Guney',              tmdbQuery:'Guney Kuzey 2011',           nombreKV:'guzey-guney', genero:'turca-drama', info:'⭐ 8.2 | 🌙 Turca | 📺 61 ep', desc:'Dos hermanos con personalidades opuestas.' },
            { titulo:'Kacak',                    tmdbQuery:'Kacak 2013',                 nombreKV:'kacak', genero:'turca-drama', info:'⭐ 7.8 | 🌙 Turca | 📺 48 ep', desc:'Un hombre inocente huye de la justicia.' },
            { titulo:'Calikusu',                 tmdbQuery:'Calikusu 2013',              nombreKV:'calikusu', genero:'turca-drama', info:'⭐ 7.7 | 🌙 Turca | 📺 39 ep', desc:'Adaptación del clásico literario turco.' },
            { titulo:'Karadayi',                 tmdbQuery:'Karadayi 2012',              nombreKV:'karadayi', genero:'turca-drama', info:'⭐ 8.0 | 🌙 Turca | 📺 93 ep', desc:'Un hombre en la Turquía de los 70 busca limpiar su nombre.' },
            // ACCIÓN
            { titulo:'Resurrection Ertugrul',    tmdbQuery:'Dirilis Ertugrul 2014',      nombreKV:'dirilis-ertugrul', genero:'turca-accion', info:'⭐ 8.1 | 🌙 Turca | 📺 150 ep', desc:'Épica histórica del guerrero otomano Ertugrul.' },
            { titulo:'Kuruluş Osman',            tmdbQuery:'Kurulus Osman 2019',         nombreKV:'kurulus-osman', genero:'turca-accion', info:'⭐ 7.9 | 🌙 Turca | 📺 100+ ep', desc:'La fundación del Imperio Otomano por Osman I.' },
            { titulo:'Poyraz Karayel',           tmdbQuery:'Poyraz Karayel 2015',        nombreKV:'poyraz-karayel', genero:'turca-accion', info:'⭐ 8.0 | 🌙 Turca | 📺 67 ep', desc:'Un agente de inteligencia turco en misiones peligrosas.' },
            { titulo:'Icerde',                   tmdbQuery:'Icerde 2016',                nombreKV:'icerde', genero:'turca-accion', info:'⭐ 8.2 | 🌙 Turca | 📺 43 ep', desc:'Dos hermanos en lados opuestos de la ley.' },
        ];
