// ─── BASE DE DATOS DORAMAS ───────────────────────────────────────────────
// 'generos' es un ARRAY (un dorama puede estar en más de una categoría).
// Slugs válidos: accion-dorama, animacion-dorama, comedia-dorama, crimen-dorama,
// documental-dorama, drama-dorama, familiar-dorama, misterio-dorama,
// ciencia-ficcion-fantasia-dorama, belica-dorama, western-dorama, romance-dorama
// (romance-dorama es categoría propia nuestra: TMDB no tiene "Romance" para TV)
        const baseDeDatosDoramas = [
            { titulo:'Nos vemos en la oficina', tmdbQuery:'내일도 출근! 2026', nombreKV:'nos-vemos-en-la-oficina', generos:['romance-dorama'], info:'⭐ 9.0 | 📺', desc:'Cha Ji-yoon lleva 7 años trabajando en el mundo corporativo y está cansada del trabajo y de las citas. Kang Si-woo, un cínico jefe con mala reputación, se cruza.' },
            { titulo:'Un sueño contigo', tmdbQuery:'그대에게 드림 2026', nombreKV:'un-sueño-contigo', generos:['romance-dorama'], info:'⭐ 7.9 | 📺', desc:'Sin sinopsis disponible.' },
            { titulo:'Novio a la carta', tmdbQuery:'월간남친 2026', nombreKV:'un-novio-por-suscripción', generos:['romance-dorama'], info:'⭐ 8.3 | 📺', desc:'Seo Mi-rae vive absorbida por el trabajo —sin tiempo para el amor— hasta que un servicio de citas despierta sentimientos que creía dormidos y abre la puerta.' },
            { titulo:'Acaramelados', tmdbQuery:'이런 엿같은 사랑 2026', nombreKV:'acaramelados', generos:['romance-dorama'], info:'⭐ 7.8 | 📺', desc:'Una fiscal ambiciosa pierde la memoria y acaba conviviendo con un entrenador de boxeo que asegura ser su novio. ¿Puede el amor verdadero nacer de una mentira?' },

            { titulo:'Hacemos lo que podemos', tmdbQuery:'모두가 자신의 무가치함과 싸우고 있다 2026', nombreKV:'hacemos-lo-que-podemos', generos:['drama-dorama'], info:'⭐ 8.5 | 📺', desc:'Tras 20 años tratando de hacer su primera película, un aspirante a director toca fondo. Pero entonces conoce a una productora saturada que le ayuda a volver.' },
            { titulo:'Así aprenderás', tmdbQuery:'참교육 2026', nombreKV:'así-aprenderás', generos:['drama-dorama'], info:'⭐ 9.4 | 📺', desc:'Unos inspectores insólitos entran en escena en los colegios, con lecciones duras de las que no aparecen en los libros de texto, para acabar con las reiteradas  faltas de respeto.' },
            { titulo:'Pro bono', tmdbQuery:'Abogado de oficio 2025', nombreKV:'pro-bono', generos:['drama-dorama'], info:'⭐ 8.3 | 📺', desc:'Un juez insigne cuya vida cambia de la noche a la mañana se suma al equipo de asistencia jurídica gratuita en un selecto bufete  Allí, la esperanza aflora en lugares insospechados.' },
            { titulo:'En tu mejor momento', tmdbQuery:'In Your Radiant Season 2026', nombreKV:'en-tu-mejor-momento', generos:['drama-dorama'], info:'⭐ 8.1 | 📺', desc:'Song Ha Ran es la diseñadora jefe de Nana Atelier, la principal casa de moda de alta gama de Corea A diferencia de su imagen impecable y aparentemente perfecta.' },
            { titulo:'El genio y los deseos', tmdbQuery:'다 이루어질지니 2025', nombreKV:'el-genio-y-los-deseos', generos:['drama-dorama','ciencia-ficcion-fantasia-dorama'], info:'⭐ 7.9 | 📺', desc:'Un excéntrico genio reaparece después de mil años para cumplir los deseos de una mujer impasible Logrará colmarla de amor e ilusión con su magia.' },
            { titulo:'GOBLIN El solitario ser inmortal', tmdbQuery:'GOBLIN: El solitario ser inmortal 2016', nombreKV:'goblin-el-solitario-ser-inmortal', generos:['drama-dorama','ciencia-ficcion-fantasia-dorama'], info:'⭐ 8.6 | 📺', desc:'Un ser inmortal desea terminar su existencia buscando en todo el mundo su novia que es la destinada a sacar la espada que le atraviesa el pecho y solo ella es.' },

            { titulo:'Un chico ejemplar', tmdbQuery:'Un chico ejemplar 2025', nombreKV:'un-chico-ejemplar', generos:['accion-dorama'], info:'⭐ 8.7 | 📺', desc:'Tras 11 años, la Policía de Insung acoge a antiguos deportistas de la selección nacional Estos medallistas que fueron héroes se enfrentan hoy a una cruda realidad.' },
            { titulo:'Perros de caza', tmdbQuery:'사냥개들 2023', nombreKV:'perros-de-caza', generos:['accion-dorama'], info:'⭐ 8.5 | 📺', desc:'Dos jóvenes boxeadores se alían con un prestamista benévolo para acabar con un despiadado usurero que se aprovecha de los más endeudados y desesperados.' },
            { titulo:'El capo del bloque', tmdbQuery:'El capo del bloque 2026', nombreKV:'el-capo-del-bloque', generos:['accion-dorama','crimen-dorama'], info:'⭐ 8.7 | 📺', desc:'Un capo se alía con una abogada en ciernes para robar el fondo de reserva de un complejo de apartamentos y acaban destapando una red de corrupción.' },
        ];
